admin:
   namespace: prod
   replicas: 1
   image: foker84/spring-petclinic-cloud-admin-server
   tag: be21cca3ea80735130c08b41a112cba799c170a8
   pullPolicy: IfNotPresent
   service:
     type: NodePort
     port: 9090
     targetPort: 9090
   
   ingress:
     enabled: false
   autoscaling:
     enabled: false
 #  env:
  #   - name: DATABASE_URI
  #     value: postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev
#     - name: CAST_SERVICE_HOST_URL
#       value: http://cast_service:8000/api/v1/casts/

gateway:
   namespace: prod
   replicas: 1
   image: foker84/spring-petclinic-cloud-api-gateway
   tag: be21cca3ea80735130c08b41a112cba799c170a8
   pullPolicy: IfNotPresent
   service:
     type: NodePort
     port: 8080
     targetPort: 8080
   resources:
     limits:
       memory: 1Gi
     requests:
       cpu: 2000m
       memory: 1Gi
   
   ingress:
     enabled: false
   autoscaling:
     enabled: false
 

vet:
   namespace: prod
   replicas: 1
   image: foker84/spring-petclinic-cloud-vets-service
   tag: be21cca3ea80735130c08b41a112cba799c170a8
   pullPolicy: IfNotPresent
   service:
     type: NodePort
     port: 8083
     targetPort: 8083
   resources:
     limits:
       memory: 1Gi
     requests:
       cpu: 2000m
       memory: 1Gi
   
   ingress:
     enabled: false
   autoscaling:
     enabled: false
 
visit:
   namespace: prod
   replicas: 1
   image: foker84/spring-petclinic-cloud--visits-service
   tag: be21cca3ea80735130c08b41a112cba799c170a8
   pullPolicy: IfNotPresent
   service:
     type: NodePort
     port: 8082
     targetPort: 8082
   resources:
     limits:
       memory: 1Gi
     requests:
       cpu: 2000m
       memory: 1Gi
   
   ingress:
     enabled: false
   autoscaling:
     enabled: false

discovery:
   namespace: prod
   replicas: 1
   image: foker84/spring-petclinic-cloud-discovery-service
   tag: be21cca3ea80735130c08b41a112cba799c170a8
   pullPolicy: IfNotPresent
   service:
     type: NodePort
     port: 8761
     targetPort: 8761
   
   ingress:
     enabled: false
   autoscaling:
     enabled: false

config:
   namespace: prod
   replicas: 1
   image: foker84/spring-petclinic-cloud--config-server
   tag: be21cca3ea80735130c08b41a112cba799c170a8
   pullPolicy: IfNotPresent
   service:
     type: NodePort
     port: 8888
     targetPort: 8888
   
   ingress:
     enabled: false
   autoscaling:
     enabled: false

customer:
   namespace: prod
   replicas: 1
<<<<<<< HEAD
#   image: openzipkin/zipkin
#   tag: 51327d88e34b05985bde9e57e0aac1d17ab058e5
   image: foker84/spring-petclinic-cloud-customer-service
   tag: 51327d88e34b05985bde9e57e0aac1d17ab058e5
=======
   image: openzipkin/zipkin
   tag: be21cca3ea80735130c08b41a112cba799c170a8
>>>>>>> 5dc2b4505279fbc12d52c06f00869d9dafc60a77
   pullPolicy: IfNotPresent
   service:
     type: NodePort
     port: 8080
     targetPort: 8080
   resources:
     limits:
       memory: 1Gi
     requests:
       cpu: 200m
       memory: 1Gi
   
   ingress:
     enabled: false
   autoscaling:
     enabled: false
   env:
     - name: JAVA_OPTS
       value: -XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom
