secretvisit:
  name: visits-db-mysql
  namespace: prod
  key: bXlzcWwtcm9vdC1wYXNzd29yZA==

secretvets:
  name: vets-db-mysql
  namespace: prod
  key: bXlzcWwtcm9vdC1wYXNzd29yZA==

secretcustomer:
  name: customers-db-mysql
  namespace: prod
  key: bXlzcWwtcm9vdC1wYXNzd29yZA==

secretwavefront:
  namespace: prod
  name: wavefront
  data:
    username: wavefront-url
    password: c3VwZXItc2VjcmV0LXBhc3N3b3Jk

admin:
   namespace: prod
   replicas: 1
   image: foker84/spring-petclinic-cloud-admin-server
   tag: be21cca3ea80735130c08b41a112cba799c170a8
   pullPolicy: IfNotPresent
   service:
     type: NodePort
     port: 9090
     targetPort: 9090
   
   ingress:
     enabled: false
   autoscaling:
     enabled: false

gateway:
   namespace: prod
   replicas: 1
   image: foker84/spring-petclinic-cloud-api-gateway
   tag: be21cca3ea80735130c08b41a112cba799c170a8
   pullPolicy: IfNotPresent
   service:
     type: NodePort
     port: 8080
     targetPort: 8080
   resources:
     limits:
       memory: 1Gi
     requests:
       cpu: 2000m
       memory: 1Gi
   
   ingress:
     enabled: false
   autoscaling:
     enabled: false
   env:
     - name: SPRING_PROFILES_ACTIVE
       value: kubernetes
     - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
       value: proxy://wavefront-proxy.spring-petclinic.svc.cluster.local:2878
 
vet:
   namespace: prod
   replicas: 1
   image: foker84/spring-petclinic-cloud-vets-service
   tag: be21cca3ea80735130c08b41a112cba799c170a8
   pullPolicy: IfNotPresent
   service:
     type: NodePort
     port: 8083
     targetPort: 8083
   resources:
     limits:
       memory: 1Gi
     requests:
       cpu: 2000m
       memory: 1Gi
   
   ingress:
     enabled: false
   autoscaling:
     enabled: false
   env:
     - name: SPRING_PROFILES_ACTIVE
       value: kubernetes
     - name: SPRING_DATASOURCE_URL
       value: jdbc:mysql://vets-db-mysql.spring-petclinic.svc.cluster.local:3306/service_instance_db?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=vets-db
     - name: SPRING_DATASOURCE_USERNAME
       value: root
     - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
       value: proxy://wavefront-proxy.spring-petclinic.svc.cluster.local:2878
   envFrom:
     - configMapRef:
         name: vets-db-mysql

 
visit:
   namespace: prod
   replicas: 1
   image: foker84/spring-petclinic-cloud--visits-service
   tag: be21cca3ea80735130c08b41a112cba799c170a8
   pullPolicy: IfNotPresent
   service:
     type: NodePort
     port: 8082
     targetPort: 8082
   resources:
     limits:
       memory: 1Gi
     requests:
       cpu: 2000m
       memory: 1Gi
   
   ingress:
     enabled: false
   autoscaling:
     enabled: false
   env:
     - name: SPRING_PROFILES_ACTIVE
       value: kubernetes
     - name: SPRING_DATASOURCE_URL
       value: jdbc:mysql://visits-db-mysql.spring-petclinic.svc.cluster.local:3306/service_instance_db?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=visits-db
     - name: SPRING_DATASOURCE_USERNAME
       value: root
     - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
       value: proxy://wavefront-proxy.spring-petclinic.svc.cluster.local:2878
   envFrom:
     - configMapRef: 
         name: visits-db-mysql

discovery:
   namespace: prod
   replicas: 1
   image: foker84/spring-petclinic-cloud-discovery-service
   tag: be21cca3ea80735130c08b41a112cba799c170a8
   pullPolicy: IfNotPresent
   service:
     type: NodePort
     port: 8761
     targetPort: 8761
   
   ingress:
     enabled: false
   autoscaling:
     enabled: false

config:
   namespace: prod
   replicas: 1
   image: foker84/spring-petclinic-cloud--config-server
   tag: be21cca3ea80735130c08b41a112cba799c170a8
   pullPolicy: IfNotPresent
   service:
     type: NodePort
     port: 8888
     targetPort: 8888
   
   ingress:
     enabled: false
   autoscaling:
     enabled: false

customer:
   namespace: prod
   replicas: 1
#   image: openzipkin/zipkin
#   tag: 51327d88e34b05985bde9e57e0aac1d17ab058e5
   image: foker84/spring-petclinic-cloud-customer-service
   tag: 51327d88e34b05985bde9e57e0aac1d17ab058e5
   pullPolicy: IfNotPresent
   service:
     type: NodePort
     port: 8080
     targetPort: 8080
   resources:
     limits:
       memory: 1Gi
     requests:
       cpu: 200m
       memory: 1Gi
   
   ingress:
     enabled: false
   autoscaling:
     enabled: false
   env:
     - name: SPRING_PROFILES_ACTIVE
       value: kubernetes
     - name: SPRING_DATASOURCE_URL
       value: jdbc:mysql://customers-db-mysql.spring-petclinic.svc.cluster.local:3306/service_instance_db?queryInterceptors=brave.mysql8.TracingQueryInterceptor&exceptionInterceptors=brave.mysql8.TracingExceptionInterceptor&zipkinServiceName=customers-db
     - name: SPRING_DATASOURCE_USERNAME
       value: root
     - name: MANAGEMENT_METRICS_EXPORT_WAVEFRONT_URI
       value: proxy://wavefront-proxy.spring-petclinic.svc.cluster.local:2878
   envFrom:
     - configMapRef:
         name: customers-db-mysql

wavefront:
   namespace: prod
   replicas: 1
   image: wavefronthq/proxy
   tag: latest
   pullPolicy: Always
   securityContext: 
     privileged: false
   ports:
     - containerPort: 2878
       protocol: TCP
     - containerPort: 9411
       protocol: TCP
   env:
     - name: WAVEFRONT_PROXY_ARGS
       value: --traceZipkinListenerPorts 9411 --traceZipkinApplicationName spring-petclinic-k8s
   envFrom: 
#     secretRef:
#       - name: wavefront
     - name: WAVEFRONT_URL
       valueFrom: 
         secretKeyRef:
           name: wavefront
           key: wavefront-url
     - name: WAVEFRONT_TOKEN
       valueFrom: 
         secretKeyRef:
           name: wavefront  
           key: wavefront-api-token

#             - WAVEFRONT_TOKEN
#             - wavefront_url
#     - name: WAVEFRONT_URL
#       secretRef:
#         name: wavefront

   service:
     type: NodePort
     ports:
       - name: http  
         port: 9411
         targetPort: 9411
         protocol: TCP
       - name: wavefront
         port: 2878
         protocol: TCP

   ingress:
     enabled: false
   autoscaling:
     enabled: false

