admin:
   namespace: dev
   replicas: 1
   image: foker84/spring-petclinic-cloud-admin-server
   tag: d4aa64ee23809a00b017e75b6e7d6e9c8c0d6dea
   pullPolicy: IfNotPresent
   service:
     type: NodePort
     port: 9090
     targetPort: 9090
   
   ingress:
     enabled: false
   autoscaling:
     enabled: false
 #  env:
  #   - name: DATABASE_URI
  #     value: postgresql://movie_db_username:movie_db_password@movie_db/movie_db_dev
#     - name: CAST_SERVICE_HOST_URL
#       value: http://cast_service:8000/api/v1/casts/

gateway:
   namespace: dev
   replicas: 1
   image: foker84/spring-petclinic-cloud-api-gateway
   tag: d4aa64ee23809a00b017e75b6e7d6e9c8c0d6dea
   pullPolicy: IfNotPresent
   service:
     type: NodePort
     port: 8080
     targetPort: 8080
   
   ingress:
     enabled: false
   autoscaling:
     enabled: false
 

vet:
   namespace: dev
   replicas: 1
   image: foker84/spring-petclinic-cloud-vets-service
   tag: d4aa64ee23809a00b017e75b6e7d6e9c8c0d6dea
   pullPolicy: IfNotPresent
   service:
     type: NodePort
     port: 8083
     targetPort: 8083
   
   ingress:
     enabled: false
   autoscaling:
     enabled: false
 
visit:
   namespace: dev
   replicas: 1
   image: foker84/spring-petclinic-cloud--visits-service
   tag: d4aa64ee23809a00b017e75b6e7d6e9c8c0d6dea
   pullPolicy: IfNotPresent
   service:
     type: NodePort
     port: 8082
     targetPort: 8082
   
   ingress:
     enabled: false
   autoscaling:
     enabled: false

discovery:
   namespace: dev
   replicas: 1
   image: foker84/spring-petclinic-cloud-discovery-server
   tag: d4aa64ee23809a00b017e75b6e7d6e9c8c0d6dea
   pullPolicy: IfNotPresent
   service:
     type: NodePort
     port: 8761
     targetPort: 8761
   
   ingress:
     enabled: false
   autoscaling:
     enabled: false

config:
   namespace: dev
   replicas: 1
   image: foker84/spring-petclinic-cloud--config-server
   tag: d4aa64ee23809a00b017e75b6e7d6e9c8c0d6dea
   pullPolicy: IfNotPresent
   service:
     type: NodePort
     port: 8888
     targetPort: 8888
   
   ingress:
     enabled: false
   autoscaling:
     enabled: false

tracing:
   namespace: dev
   replicas: 1
   image: openzipkin/zipkin
   tag: d4aa64ee23809a00b017e75b6e7d6e9c8c0d6dea
   pullPolicy: IfNotPresent
   service:
     type: NodePort
     port: 9411
     targetPort: 9411
   
   ingress:
     enabled: false
   autoscaling:
     enabled: false
 env:
     - name: JAVA_OPTS
       value: -XX:+UnlockExperimentalVMOptions -Djava.security.egd=file:/dev/./urandom

