apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "petclinichelm.fullname" . }}-gateway
  namespace: {{ .Values.gateway.namespace }}
  labels:
    {{- include "petclinichelm.labels" . | nindent 4 }}
spec:
  {{- if not .Values.gateway.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "petclinichelm.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "petclinichelm.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{/*  serviceAccountName: {{ include "petclinichelm.serviceAccountName" . }} 
*/}}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.gateway.image }}:{{ .Values.gateway.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.gateway.pullPolicy }}
          env:
            {{- range .Values.gateway.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }} 
{{/*          ports:
            - name: http
              containerPort: {{ .Values.gateway.service.containerPort }}
              protocol: TCP */}}
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            limits:
              memory: {{ .Values.vet.resources.limits.memory }}
            requests:
              cpu: {{ .Values.vet.resources.requests.cpu }}
              memory: {{ .Values.vet.resources.requests.memory }}
          {{- with .Values.volumeMounts }}
          volumeMounts:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      {{- with .Values.volumes }}
      volumes:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
