apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretwavefront.name }}
  namespace: {{ .Values.secretwavefront.namespace }}
data:
  username:{{ .Values.secretwavefront.data.usernamxe }}
  password: {{ .Values.secretwavefront.data.password }}
{{/*  password: {{ .Values.secretwavefront.key }} */}}
{{/*
{{- range $key, $value := $.Values.secretwavefront.keys }}
  - name: {{ .name }}
    key: {{ .key }}
  {{- end }}
*/}}
 
