apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretwavefront.name }}
  namespace: {{ .Values.secretwavefront.namespace }}
data:
{{/*  password: {{ .Values.secretwavefront.key }} */}}
{{- range $key, $value := $.Values.secretwavefront.keys }}
  - name: {{ .name }}
    key: {{ .key }}
  {{- end }}

