apiVersion: v1
kind: Service
metadata:
  name: {{ include "petclinichelm.fullname" . }}-wavefront
  namespace: {{ .Values.wavefront.namespace }}
  labels:
    {{- include "petclinichelm.labels" . | nindent 4 }}
spec:
  ports:
    {{- range .Values.wavefront.service.ports }}
    - port: {{ .port }}
      targetPort: {{ .targetPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "petclinichelm.selectorLabels" . | nindent 4 }}
