apiVersion: v1
kind: Service
metadata:
  name: {{ include "petclinichelm.fullname" . }}
  labels:
    {{- include "petclinichelm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service }}
  ports:
    - port: {{ .Values.service }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "petclinichelm.selectorLabels" . | nindent 4 }}
